//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

pub use super::post::Entity as Post;
pub use super::proposal::Entity as Proposal;
pub use super::space::Entity as Space;
pub use super::user::Entity as User;
pub use serde::{Serialize, Deserialize};