//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "vote_type")]
pub enum VoteType {
    #[sea_orm(string_value = "Abstain")]
    Abstain,
    #[sea_orm(string_value = "Against")]
    Against,
    #[sea_orm(string_value = "For")]
    For,
}
