//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "space")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub about: Option<String>,
    pub avatar: Option<String>,
    pub symbol: Option<String>,
    pub token_address: Option<String>,
    pub governance_contract_address: Option<String>,
    pub twitter: Option<String>,
    pub discord: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub terms: Option<String>,
    pub admins: Option<Json>,
    pub authors: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::proposal::Entity")]
    Proposal,
}

impl Related<super::proposal::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Proposal.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
